# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    feature.leads.enabled: '%env(bool:LEADS_FEATURE_ENABLED)%'
    lead.claim_ttl_minutes: '%env(int:LEAD_CLAIM_TTL_MINUTES)%'
    alerts.admin_email: '%env(string:ALERT_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Infrastructure\Doctrine\SlugListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    App\Infrastructure\Doctrine\ContentSanitizerListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\Seed\Seeder:
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FeatureFlags:
        arguments:
            $featureLeadsEnabled: '%feature.leads.enabled%'

    # Captcha verifier (null by default; enable via env if needed)
    App\Service\Captcha\CaptchaVerifierInterface: '@App\Service\Captcha\NullCaptchaVerifier'
    App\Service\Captcha\NullCaptchaVerifier:
        arguments:
            $enabled: '%env(bool:CAPTCHA_ENABLED)%'

    App\MessageHandler\DispatchLeadMessageHandler:
        arguments:
            $claimTtlMinutes: '%lead.claim_ttl_minutes%'
            $appBaseUrl: '%env(APP_BASE_URL)%'
            $outreachFrom: '%env(OUTREACH_CONTACT_EMAIL)%'
            $companyName: '%env(OUTREACH_COMPANY_NAME)%'
            $alertsRecipient: '%alerts.admin_email%'
            $recipientTokenFactory: '@App\Service\Lead\LeadRecipientTokenFactory'
            $urlBuilder: '@App\Service\Lead\LeadUrlBuilder'
            $emailFactory: '@App\Service\Lead\OutreachEmailFactory'

    App\Service\Lead\LeadUrlBuilder:
        arguments:
            $appBaseUrl: '%env(APP_BASE_URL)%'

    App\Service\Lead\OutreachEmailFactory:
        arguments:
            $fromAddress: '%env(OUTREACH_CONTACT_EMAIL)%'
            $companyName: '%env(OUTREACH_COMPANY_NAME)%'
            $companyAddress: '%env(string:OUTREACH_COMPANY_ADDRESS)%'
            $contactEmail: '%env(OUTREACH_CONTACT_EMAIL)%'
 
    App\Command\SendTestEmailCommand:
        arguments:
            $defaultFrom: '%env(OUTREACH_CONTACT_EMAIL)%'

    Symfony\Component\HttpFoundation\UriSigner:
        arguments:
            $secret: '%kernel.secret%'
            $hashParameter: 'signature'
