# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    feature.leads.enabled: '%env(bool:LEADS_FEATURE_ENABLED)%'
    lead.claim_ttl_minutes: '%env(int:LEAD_CLAIM_TTL_MINUTES)%'
    alerts.admin_email: '%env(string:ALERT_EMAIL)%'
    feature.lead_claim_undo: '%env(bool:FEATURE_LEAD_CLAIM_UNDO)%'
    lead.undo_window_minutes: '%env(int:LEAD_UNDO_WINDOW_MINUTES)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Infrastructure\Doctrine\SlugListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    App\Infrastructure\Doctrine\ContentSanitizerListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\Seed\Seeder:
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FeatureFlags:
        arguments:
            $featureLeadsEnabled: '%feature.leads.enabled%'

    # CAPTCHA configuration
    # Provider-aware delegating verifier; chooses implementation via env CAPTCHA_PROVIDER
    App\Service\Captcha\CaptchaVerifierInterface: '@App\Service\Captcha\ProviderAwareCaptchaVerifier'
    App\Service\Captcha\ProviderAwareCaptchaVerifier:
        arguments:
            $provider: '%env(string:CAPTCHA_PROVIDER)%'
            $nullVerifier: '@App\Service\Captcha\NullCaptchaVerifier'
            $recaptchaVerifier: '@?App\Service\Captcha\RecaptchaVerifier'
            $hcaptchaVerifier: '@?App\Service\Captcha\HcaptchaVerifier'
    App\Service\Captcha\NullCaptchaVerifier:
        arguments:
            $enabled: '%env(bool:CAPTCHA_ENABLED)%'
    App\Service\Captcha\RecaptchaVerifier:
        arguments:
            $secretKey: '%env(string:RECAPTCHA_SECRET)%'
    App\Service\Captcha\HcaptchaVerifier:
        arguments:
            $secretKey: '%env(string:HCAPTCHA_SECRET)%'

    App\MessageHandler\DispatchLeadMessageHandler:
        arguments:
            $claimTtlMinutes: '%lead.claim_ttl_minutes%'
            $appBaseUrl: '%env(APP_BASE_URL)%'
            $outreachFrom: '%env(OUTREACH_CONTACT_EMAIL)%'
            $companyName: '%env(OUTREACH_COMPANY_NAME)%'
            $alertsRecipient: '%alerts.admin_email%'
            $recipientTokenFactory: '@App\Service\Lead\LeadRecipientTokenFactory'
            $urlBuilder: '@App\Service\Lead\LeadUrlBuilder'
            $emailFactory: '@App\Service\Lead\OutreachEmailFactory'

    App\Service\Lead\LeadUrlBuilder:
        arguments:
            $appBaseUrl: '%env(APP_BASE_URL)%'

    App\Service\Lead\LeadClaimService:
        arguments:
            $enableUndo: '%feature.lead_claim_undo%'
            $undoWindowMinutes: '%lead.undo_window_minutes%'

    App\Service\Lead\OutreachEmailFactory:
        arguments:
            $fromAddress: '%env(OUTREACH_CONTACT_EMAIL)%'
            $companyName: '%env(OUTREACH_COMPANY_NAME)%'
            $companyAddress: '%env(string:OUTREACH_COMPANY_ADDRESS)%'
            $contactEmail: '%env(OUTREACH_CONTACT_EMAIL)%'
 
    App\Command\SendTestEmailCommand:
        arguments:
            $defaultFrom: '%env(OUTREACH_CONTACT_EMAIL)%'

    Symfony\Component\HttpFoundation\UriSigner:
        arguments:
            $secret: '%kernel.secret%'
            $hashParameter: 'signature'

    App\Controller\LeadClaimController:
        arguments:
            $featureLeadClaimUndo: '%feature.lead_claim_undo%'
