# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    lead_feature_enabled: '%env(bool:LEADS_FEATURE_ENABLED)%'
    'sms.provider': '%env(string:SMS_PROVIDER)%'
    'twilio.sid': '%env(string:TWILIO_SID)%'
    'twilio.token': '%env(string:TWILIO_TOKEN)%'
    'twilio.from': '%env(string:TWILIO_FROM)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Infrastructure\Doctrine\SlugListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    App\Infrastructure\Doctrine\ContentSanitizerListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\Seed\Seeder:
        public: true

    # SMS Gateways
    App\Service\Sms\TwilioSmsGateway:
        arguments:
            $sid: '%twilio.sid%'
            $token: '%twilio.token%'
            $from: '%twilio.from%'

    # Default alias; overridden by compiler pass based on SMS_PROVIDER
    App\Service\Sms\SmsGatewayInterface: '@App\\Service\\Sms\\NullSmsGateway'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
