name: Codex Runner

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-codex-task:
    runs-on: ubuntu-latest

    env:
      SLEEP_SECONDS: 300
      NOOP_COMMIT: true
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Node.js (for other tools, not Codex CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install project dependencies
        run: make setup

      - name: Install Codex CLI (static Linux binary)
        run: |
          set -euxo pipefail
      
          # Fetch latest release tag from GitHub
          rel="$(curl -s https://api.github.com/repos/openai/codex/releases/latest | jq -r .tag_name)"
      
          # Download and extract static binary
          curl -L -o codex.tar.gz "https://github.com/openai/codex/releases/download/${rel}/codex-x86_64-unknown-linux-musl.tar.gz"
          tar -xzf codex.tar.gz
      
          # Move to bin and make executable
          mv codex-x86_64-unknown-linux-musl /usr/local/bin/codex
          chmod +x /usr/local/bin/codex
      
          # Final working validation – no dry run
          codex exec "noop test run" --full-auto
      
          echo "CODEX_CMD=/usr/local/bin/codex" >> "$GITHUB_ENV"

      - name: Debug Codex CLI location
        run: |
          set -euxo pipefail
          which codex || true
          type -a codex || true
          echo "CODEX_CMD = ${CODEX_CMD:-unset}"

      - name: Run Codex task with retries
        run: bash scripts/run_codex_task.sh "$TASK_ID" "$TASK_TITLE" "$attempt"
        env:
          TASK_ID: "task-id-placeholder"
          TASK_TITLE: "Update the README file formatting"
          attempt: "1"
          GITHUB_REPOSITORY: ${{ github.repository }}