name: Codex Runner

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-codex-task:
    runs-on: ubuntu-latest

    env:
      SLEEP_SECONDS: 300
      NOOP_COMMIT: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Node (needed for other steps if any)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install project dependencies
        run: make setup

      - name: Install Codex CLI (static Linux binary)
        run: |
          set -euxo pipefail
          # Get latest release tag
          rel="$(curl -s https://api.github.com/repos/openai/codex/releases/latest | jq -r .tag_name)"

          # Download Linux musl binary
          curl -L -o codex.tar.gz "https://github.com/openai/codex/releases/download/${rel}/codex-x86_64-unknown-linux-musl.tar.gz"
          tar -xzf codex.tar.gz

          # Move to /usr/local/bin and make executable
          mv codex-x86_64-unknown-linux-musl /usr/local/bin/codex
          chmod +x /usr/local/bin/codex

          # Confirm it works
          codex exec "noop test run" --full-auto . --dry-run

          # Export the binary path to environment
          echo "CODEX_CMD=/usr/local/bin/codex" >> "$GITHUB_ENV"

      - name: Debug Codex CLI location
        run: |
          which codex || true
          type -a codex || true
          echo "CODEX_CMD = $CODEX_CMD"

      - name: Run Codex task with retries
        run: bash scripts/run_codex_task.sh "$TASK_ID" "$TASK_TITLE" "$attempt"
        env:
          TASK_ID: "task-id-placeholder"
          TASK_TITLE: "Update the README file formatting"
          attempt: "1"
