name: E2E (Cypress)

on:
  pull_request:
    branches:
      - staging

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_sqlite

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Prepare test DB (SQLite) and seed
        run: |
          php bin/console --env=test doctrine:migrations:migrate --no-interaction --allow-no-migration
          php bin/console --env=test app:seed

      - name: Start PHP server
        run: php -S 127.0.0.1:8080 -t public public/index.php &

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: 'http://127.0.0.1:8080/'
          env: CYPRESS_BASE_URL=http://127.0.0.1:8080

