name: Production Data Retention

on:
  schedule:
    - cron: '15 3 * * *' # Daily at 03:15 UTC
  workflow_dispatch: {}

concurrency:
  group: prod-retention
  cancel-in-progress: false

jobs:
  retention:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
    steps:
      - name: Run retention on production host
        shell: bash
        run: |
          set -euo pipefail
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no "$EC2_USER"@"$EC2_HOST" \
            "cd /var/www/cleanwhiskers.com && /usr/bin/php bin/console app:leads:retention --env=prod"
