name: Deploy to Staging 

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_ENV: staging
      STAGING_RDS_ENDPOINT: ${{ secrets.STAGING_RDS_ENDPOINT }}
      STAGING_DB_USER: ${{ secrets.STAGING_DB_USER }}
      STAGING_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_STAGING_HOST: ${{ secrets.EC2_STAGING_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      # Optional: set these to enable Apache Basic Auth on staging
      STAGING_BASIC_AUTH_USER: ${{ secrets.STAGING_BASIC_AUTH_USER }}
      STAGING_BASIC_AUTH_PASS: ${{ secrets.STAGING_BASIC_AUTH_PASS }}

    steps:
      - name: Checkout latest staging branch
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Pull latest code from staging
        run: |
          git checkout staging
          git pull origin staging

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip, intl, mbstring, curl, bcmath, xml

      - name: Set .env file
        run: |
          cp .env.staging .env
          envsubst '$STAGING_RDS_ENDPOINT $STAGING_DB_USER $STAGING_DB_PASSWORD' < .env > .env.tmp
          mv .env.tmp .env

      - name: Install PHP Dependencies
        env:
          SKIP_CACHE_CLEAR: "1"
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'   # pin exact LTS to avoid surprises
          cache: 'yarn'
  
      - name: Verify Node.js version
        run: |
            node -v
            node -e "const v=+process.versions.node.split('.')[0]; if(v<20){console.error('Need Node >=20, got', process.version); process.exit(1)} else {console.log('Using', process.version)}"
  
      - name: Install Node.js Dependencies
        run: yarn install
          # If you need to unblock temporarily, swap to:
          # run: yarn install --ignore-engines

      - name: Build Frontend Assets
        run: yarn build


      - name: Compile Asset Map
        run: php bin/console asset-map:compile

      - name: Deploy to Staging Server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --delete --exclude 'node_modules' --exclude '.git' --exclude 'var' -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" . $EC2_USER@$EC2_STAGING_HOST:/var/www/staging.cleanwhiskers.com

      - name: Configure Basic Auth on Staging (optional)
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          # Create or update .htpasswd only when both user and pass are provided
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_STAGING_HOST \
          "set -euo pipefail; \
           cd /var/www/staging.cleanwhiskers.com; \
           if [ -n '${STAGING_BASIC_AUTH_USER}' ] && [ -n '${STAGING_BASIC_AUTH_PASS}' ]; then \
             if command -v htpasswd >/dev/null 2>&1; then \
               htpasswd -bc .htpasswd '${STAGING_BASIC_AUTH_USER}' '${STAGING_BASIC_AUTH_PASS}'; \
             else \
               # Fallback if apache2-utils not installed: generate crypt hash via OpenSSL
               HASH=\"$(openssl passwd -apr1 '${STAGING_BASIC_AUTH_PASS}')\"; \
               printf '%s:%s\n' '${STAGING_BASIC_AUTH_USER}' "$HASH" > .htpasswd; \
             fi; \
             chmod 640 .htpasswd; \
           else \
             echo 'STAGING_BASIC_AUTH_USER/PASS not set; skipping .htpasswd configuration'; \
           fi"

      - name: Run Migrations on Staging Server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_STAGING_HOST \
          "cd /var/www/staging.cleanwhiskers.com && php bin/console --no-interaction --allow-no-migration doctrine:migrations:migrate"

      - name: Install Importmap on Staging Server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_STAGING_HOST \
          "cd /var/www/staging.cleanwhiskers.com && php bin/console importmap:install"

      - name: Clear Cache on Staging Server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_STAGING_HOST \
          "cd /var/www/staging.cleanwhiskers.com && sudo rm -rf var/cache/prod && mkdir var/cache/prod"

      - name: Set Cache Directory Permissions on Staging Server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_STAGING_HOST \
          "cd /var/www/staging.cleanwhiskers.com && sudo chown -R www-data:www-data var/cache/prod && sudo chmod -R 775 var/cache/prod/"

      - name: Ensure Logs Directory on Staging Server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_STAGING_HOST \
          "cd /var/www/staging.cleanwhiskers.com && mkdir -p var/log && sudo chown -R www-data:www-data var/log && sudo chmod -R 775 var/log"
